version: '3.8'

services:
  frontend:
    build: ./frontend
    networks: [ app-net ]
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

  backend:
    build: ./backend
    networks: [ app-net, db-net ]
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/appdb  
    depends_on:
      - database
    ports:
      - "5000:5000"

  database:
    image: postgres:15-alpine
    networks: [ db-net ]
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks: [ app-net ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
  db-net:
    driver: bridge

volumes:
  db-data:
    driver: local
