version: '3.8'

services:
  frontend:
    image: mystack_frontend:latest
    networks:
      - app-net
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    ports:
      - "80:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  backend:
    image: mystack_backend:latest
    networks:
      - app-net
      - db-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/appdb
    depends_on:
      - database
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  database:
    image: postgres:15-alpine
    networks:
      - db-net
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      restart_policy:
        condition: any

networks:
  app-net:
    driver: overlay
  db-net:
    driver: overlay

volumes:
  db-data:
    driver: local
